Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,27 @@
-# This is a basic workflow to help you get started with Actions
+name: Check commit message
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  workflow_dispatch:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
   pull_request:
-    branches: [ "main" ]
+    types:
+      - opened
+      - synchronize
+      - reopened
+  push:
+    branches:
+      - main
 
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  check_commit_message:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-        
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Check commit message format
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          commits=$(git log --format=%B -n 1)
+          if ! [[ "$commits" =~ ^JIRA-[0-9]+ ]]; then
+            echo "Error: Commit message must start with a JIRA issue key (e.g., JIRA-12345)."
+            exit 1
+          fi
