Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -16,13 +16,18 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v2
-
+        with:
+          fetch-depth: 0
+          ref: ${{github.event.after}}
       - name: Check commit message format
         run: |
-          commits=$(git log --format=%B -n 1)
-          if ! [[ "$commits" =~ ^JIRA-[0-9]+ ]]; then
-            echo "Error: Commit message must start with a JIRA issue key (e.g., JIRA-12345)."
-            exit 1
-          fi
+          MSG=$(git log --format=%B  ${{github.event.after}})
+          echo $MSG
+        
+          #commits=$(git log --format=%B -n 1)
+          # if ! [[ "$commits" =~ ^JIRA-[0-9]+ ]]; then
+          #   echo "Error: Commit message must start with a JIRA issue key (e.g., JIRA-12345)."
+          #   exit 1
+          # fi
